MECCA.scene({ id: 'zz-test', build({ root, tl, h, P, bg, onFrame, cue }) {
  const ic = h.icon({ size: 420, parent: root });
  Object.assign(ic.svg.style, { position: 'absolute', left: '1300px', top: '330px' });
  tl.from(ic.arcOuter, { drawSVG: '0%', duration: 1.2, ease: 'mecca.inOut' }, 0);
  tl.from(ic.arcInner, { drawSVG: '0%', duration: 1.0, ease: 'mecca.inOut' }, 0.3);
  tl.from(ic.pupil, { scale: 0, transformOrigin: '50% 50%', duration: 0.8, ease: 'mecca.back' }, 0.8);
  const lg = h.logo({ width: 700, parent: root }); Object.assign(lg.svg.style, { position: 'absolute', left: '120px', top: '820px' });
  h.eyebrow('— A máquina que faz a sua empresa girar', { x: 120, y: 120, parent: root });
  const t = h.text('Somos o<br><em>meccanismo.</em>', { x: 120, y: 200, size: 170, parent: root });
  const sp = h.split(t, { type: 'lines,chars', mask: 'lines' });
  tl.from(sp.chars, { yPercent: 110, stagger: 0.02, duration: 0.7, ease: 'mecca.out' }, 0.5);
  const s = h.svg('svg', { class: 'fill' }, root);
  const g = h.gear(s, { x: 900, y: 700, r: 140, teeth: 14, stroke: P.lavender, strokeWidth: 3, fill: 'rgba(124,58,237,0.15)' });
  const g2 = h.gear(s, { x: 900 + 140 + 96 - 18, y: 700, r: 96, teeth: 10, stroke: P.magenta, strokeWidth: 3 });
  tl.to(g.rot, { rotation: 360, svgOrigin: '0 0', duration: 6, ease: 'none' }, 0);
  tl.to(g2.rot, { rotation: -360 * 14 / 10, svgOrigin: '0 0', duration: 6, ease: 'none' }, 0);
  const { ctx } = h.canvas(root);
  onFrame((lt) => { ctx.clearRect(0, 0, 1920, 1080); h.orbit(ctx, { cx: 1510, cy: 540, rx: 380, ry: 150, rot: -0.3, alpha: 0.35 });
    const p = h.ellipsePt(1510, 540, 380, 150, -0.3, lt * 1.3); h.glowDot(ctx, p.x, p.y, 7, P.magenta, 1); });
  const c = h.chip('CRM operado, não só implantado', { x: 120, y: 620, parent: root });
  h.strike(tl, t, 2.5);
  h.flash(tl, root, 3, {});
  tl.to(bg, { grid: 1, duration: 1 }, 0);
  cue(0.5, 'whoosh'); cue(3, 'impact');
} });
